# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be357034dad4e74f3496ea6a3cc0f5ce138a8788f79a637a3db3ced9d33cf110b4b5755ec4b815eacf46ec23d9bd03fc3f13d8c5b1d3de519a764f7322af6b20

test:
  secret_key_base: 3e210e70427c95ea7ce1740cdbeb0d329ff3a66980b02ce49f88998758f052e34feed630d6f63e57e8cbd3a50204b754c9d839600a8ec54414c822f82d4f4e87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
